/** Row audit fields aligned with database `*_user_id` columns */
export interface AuditFields {
  createdByUserId: string | null;
  updatedByUserId: string | null;
  deletedByUserId: string | null;
  createdAt: string;
  updatedAt: string | null;
  deletedAt: string | null;
}

export type UUID = string;

export type {
  AuthResponse,
  AuthMe,
  AuthTokens,
  AuthUser,
  ForgotPasswordRequest,
  ForgotPasswordResponse,
  LoginRequest,
  LogoutResponse,
  RefreshTokenRequest,
  RegisterRequest,
  ResetPasswordRequest,
  ResetPasswordResponse,
  UserStatus,
  VerifyOperationRequest,
} from './auth.js';

export type {
  CreateUserAddressRequest,
  CreateUserPaymentMethodRequest,
  LoyaltyAccount,
  AdminLoyaltyAccountListItem,
  AdjustLoyaltyPointsRequest,
  AdjustLoyaltyPointsResponse,
  LoyaltyAccountsListQuery,
  LoyaltyTier,
  UpdateProfileRequest,
  UpdateUserAddressRequest,
  UpdateUserPaymentMethodRequest,
  UserAddress,
  UserAddressesListQuery,
  UserPaymentMethod,
  UserPaymentMethodsListQuery,
  UserPaymentMethodType,
  UserSession,
  UserSessionsListQuery,
} from './account.js';

export type {
  PaginatedResponse,
  PaginationMeta,
  PaginationQuery,
  PaymentStatus,
  SucceededPaymentsRevenue,
} from './pagination.js';

export type {
  PaymentAdminDetail,
  PaymentListItem,
  PaymentsListQuery,
  RefundPaymentRequest,
} from './payment.js';

export type {
  CreatePromoCodeRequest,
  PromoCode,
  PromoCodeDiscountType,
  PromoCodesListQuery,
  UpdatePromoCodeRequest,
} from './promo-code.js';

export type {
  CreatePromotionRequest,
  Promotion,
  PromotionsListQuery,
  UpdatePromotionRequest,
} from './promotion.js';

export type {
  CreateOrganizationRequest,
  Organization,
  OrganizationListItem,
  OrganizationStatus,
  OrganizationsListQuery,
  UpdateOrganizationRequest,
} from './organization.js';

export type {
  Airline,
  AirlinesListQuery,
  Airport,
  AirportsListQuery,
  BulkUpsertFlightClassAvailabilityRequest,
  BulkUpsertFlightClassAvailabilityResponse,
  CreateAirlineRequest,
  CreateAirportRequest,
  CreateFlightClassAvailabilityRequest,
  CreateFlightClassRequest,
  CreateFlightImageRequest,
  CreateFlightRequest,
  Flight,
  FlightClass,
  FlightClassAvailability,
  FlightClassAvailabilityListQuery,
  FlightClassName,
  FlightClassesListQuery,
  FlightImage,
  FlightImagesListQuery,
  FlightsListQuery,
  UpdateAirlineRequest,
  UpdateAirportRequest,
  UpdateFlightClassAvailabilityRequest,
  UpdateFlightClassRequest,
  UpdateFlightImageRequest,
  UpdateFlightRequest,
} from './flight.js';

export type {
  Cabin,
  CabinAvailability,
  CabinAvailabilityListQuery,
  CabinsListQuery,
  CreateCabinAvailabilityRequest,
  CreateCabinRequest,
  CreateCruiseLineRequest,
  CreateCruisePortRequest,
  CreateCruiseSailingRequest,
  CreateItineraryPortRequest,
  CreateItineraryRequest,
  CreateShipRequest,
  CreateShipImageRequest,
  CruiseLine,
  CruiseLinesListQuery,
  CruisePort,
  CruisePortsListQuery,
  CruiseSailing,
  CruiseSailingsListQuery,
  Itinerary,
  ItinerariesListQuery,
  ItineraryPort,
  ItineraryPortsListQuery,
  Ship,
  ShipImage,
  ShipImagesListQuery,
  ShipsListQuery,
  UpdateCabinAvailabilityRequest,
  UpdateCabinRequest,
  UpdateCruiseLineRequest,
  UpdateCruisePortRequest,
  UpdateCruiseSailingRequest,
  UpdateItineraryPortRequest,
  UpdateItineraryRequest,
  UpdateShipRequest,
  UpdateShipImageRequest,
} from './cruise.js';

export type {
  CreateRentalAgencyRequest,
  CreateVehicleAvailabilityRequest,
  CreateVehicleCategoryRequest,
  CreateVehicleImageRequest,
  CreateVehicleRequest,
  RentalAgenciesListQuery,
  RentalAgency,
  UpdateRentalAgencyRequest,
  UpdateVehicleAvailabilityRequest,
  UpdateVehicleCategoryRequest,
  UpdateVehicleImageRequest,
  UpdateVehicleRequest,
  Vehicle,
  VehicleAvailability,
  VehicleAvailabilityListQuery,
  VehicleAvailabilityStatus,
  VehicleCategoriesListQuery,
  VehicleCategory,
  VehicleImage,
  VehicleImagesListQuery,
  VehiclesListQuery,
} from './car-rental.js';

export type {
  Activity,
  ActivitiesListQuery,
  ActivityDifficultyLevel,
  ActivityImage,
  ActivityImagesListQuery,
  ActivityProvider,
  ActivityProvidersListQuery,
  ActivitySchedule,
  ActivitySchedulesListQuery,
  CreateActivityProviderRequest,
  CreateActivityImageRequest,
  CreateActivityRequest,
  CreateActivityScheduleRequest,
  UpdateActivityProviderRequest,
  UpdateActivityImageRequest,
  UpdateActivityRequest,
  UpdateActivityScheduleRequest,
} from './activity.js';

export type {
  Booking,
  BookingAdminDetail,
  BookingClient,
  BookingListItem,
  BookingPayment,
  BookingStatusHistoryEntry,
  ApproveBookingRequest,
  ApproveTravelerPricingRequest,
  UpdateBookingPricingRequest,
  UpdateBookingVisitDatesRequest,
  RejectBookingRequest,
  BookingCheckoutSessionResponse,
  BookingPaymentIntentResponse,
  RefundPaymentResponse,
  CancelBookingRequest,
  RecordCashPaymentRequest,
  UpdateBookingStatusRequest,
  BookingCheckoutItem,
  BookingCheckoutItemType,
  BookingCheckoutLine,
  AppliedCheckoutDiscount,
  BookingCheckoutPreview,
  BookingCheckoutRequest,
  BookingIdentityDocument,
  BookingIdentityDocumentStatus,
  BookingIdentityDocumentType,
  ReviewBookingIdentityDocumentRequest,
  BookingManifestEntry,
  BookingManifestSex,
  CreateBookingManifestEntryRequest,
  UpdateBookingManifestEntryRequest,
  BookingDetail,
  CreateBookingResponse,
  BookingMessage,
  BookingMessagesList,
  BookingRequestResponse,
  CreateBookingMessageRequest,
  BookingItem,
  BookingItemListItem,
  BookingItemType,
  BookingItemsListQuery,
  BookingsListQuery,
  BookingStatus,
} from './booking.js';

export {
  BOOKING_ITEM_TYPE_KEYS,
  DEFAULT_BOOKING_ITEM_TYPE_MODES,
  isBookingMode,
  normalizeBookingItemTypeModes,
  resolveBookingModeForItemType,
  resolveCheckoutBookingMode,
} from './tour-guide.js';

export type {
  BookingGuideAssignment,
  BookingGuideRole,
  BookingItemTypeKey,
  BookingItemTypeModes,
  BookingMode,
  ResolvedBookingItemTypeModes,
  TourGuide,
  TourGuideStatus,
  TourGuideType,
  TourGuideUserSummary,
  TourGuidesListQuery,
  CreateTourGuideRequest,
  UpdateTourGuideRequest,
  AssignBookingGuideItem,
  AssignBookingGuidesRequest,
} from './tour-guide.js';

export type {
  BlogPost,
  BlogPostStatus,
  BlogPostsListQuery,
  CreateBlogPostRequest,
  PublicBlogPostDetail,
  PublicBlogPostListItem,
  PublicBlogPostsListQuery,
  UpdateBlogPostRequest,
} from './blog-post.js';

export type {
  AdminReviewDetail,
  AdminReviewListItem,
  CreateBookingReviewRequest,
  GuideReviewInvite,
  PropertyReviewSummary,
  PropertyReviewsListQuery,
  Review,
  ReviewEntityType,
  ReviewStatus,
  ReviewsListQuery,
  UpdateReviewStatusRequest,
} from './review.js';

export type {
  AdminSupportTicketDetail,
  AdminSupportTicketListItem,
  CreateSupportMessageRequest,
  CreateSupportMessageResponse,
  CreateSupportTicketRequest,
  SupportTicket,
  SupportTicketCreated,
  SupportTicketMessage,
  SupportTicketPriority,
  SupportTicketStatus,
  SupportTicketsListQuery,
  UpdateSupportTicketRequest,
} from './support.js';

export type {
  CreatePackageImageRequest,
  CreatePackageItemRequest,
  CreatePackageRequest,
  Package,
  PackageDetail,
  PackageImage,
  PackageImagesListQuery,
  PackageItem,
  PackageItemEnriched,
  PackageItemType,
  PackageItemsListQuery,
  PackagePricing,
  PackageSuggestedImage,
  PackageSuggestedImageGroup,
  PackagesListQuery,
  UpdatePackageImageRequest,
  UpdatePackageItemRequest,
  UpdatePackageRequest,
} from './package.js';

export type {
  CreateDestinationRequest,
  CreatePointOfInterestRequest,
  Destination,
  DestinationRelatedCounts,
  DestinationsListQuery,
  PointOfInterest,
  PointsOfInterestListQuery,
  PublicDestinationHighlight,
  UpdateDestinationRequest,
  UpdatePointOfInterestRequest,
} from './destination.js';

export type {
  Amenity,
  AmenitiesListQuery,
  CreateAmenityRequest,
  CreatePropertyImageRequest,
  CreatePropertyRequest,
  CreateRoomAvailabilityRequest,
  CreateRoomImageRequest,
  CreateRoomRequest,
  BulkUpsertRoomAvailabilityRequest,
  BulkUpsertRoomAvailabilityResponse,
  Property,
  PropertyAmenitiesListQuery,
  PropertyAmenitiesPayload,
  PropertyAmenity,
  PropertiesListQuery,
  PropertyImage,
  PropertyImagesListQuery,
  PropertyType,
  ReplacePropertyAmenitiesRequest,
  Room,
  RoomAvailability,
  RoomAvailabilityListQuery,
  RoomImage,
  RoomImagesListQuery,
  RoomsListQuery,
  UpdateAmenityRequest,
  UpdateRoomAvailabilityRequest,
  UpdatePropertyImageRequest,
  UpdatePropertyRequest,
  UpdateRoomImageRequest,
  UpdateRoomRequest,
  PropertySearchQuery,
  PropertySearchResult,
  PropertyDetail,
  PropertyDetailQuery,
  PropertyDetailImage,
  PropertyDetailAmenity,
  PropertyDetailRoom,
  PropertyDetailNightlyPrice,
  PropertyDetailStay,
  PropertyCalendarDay,
  PublicDestination,
} from './accommodation.js';

export type {
  BookingDefaultsValue,
  BrandingPlatformValue,
  BulkUpsertOrganizationSettingsRequest,
  ContactWebSettingValue,
  CreateOrganizationBankAccountRequest,
  EmailBrandingValue,
  EmailPreviewRequest,
  EmailPreviewResponse,
  EmailPreviewTemplate,
  LocaleSettingValue,
  LoyaltyOneKeySettingValue,
  OrganizationBankAccount,
  OrganizationBankAccountsListQuery,
  OrganizationSetting,
  OrganizationSettingsListQuery,
  PublicContact,
  PublicAuthVisual,
  PublicAuthVisualIcon,
  AuthVisualDecorIcon,
  AuthVisualIconPosition,
  AuthVisualIconPreset,
  AuthVisualIconSize,
  AuthVisualSettingValue,
  UpdateOrganizationBankAccountRequest,
  UpsertOrganizationSettingItem,
} from './organization-settings.js';

export type {
  CreateUserRequest,
  UpdateUserRequest,
  User,
  UsersListQuery,
} from './user.js';

export type {
  CreateEmployeeRequest,
  Employee,
  EmployeeStatus,
  EmployeeUserSummary,
  EmployeesListQuery,
  UpdateEmployeeRequest,
} from './employee.js';

export type {
  CreateRoleRequest,
  CreateUserRoleAssignmentRequest,
  Permission,
  PermissionsListQuery,
  RbacAuditActor,
  RbacAuditEventType,
  RbacAuditLog,
  RbacAuditLogsListQuery,
  ReplaceRolePermissionsRequest,
  Role,
  RolePermissionsPayload,
  RolesListQuery,
  ScopeType,
  UpdateRoleRequest,
  UserRoleAssignment,
  UserRoleAssignmentsListQuery,
} from './rbac.js';
