export const posSalePageConfig = {
  title: 'Nouvelle vente',
  subtitle: 'Recherchez un produit, ajoutez au panier et encaissez.',
  backToHomeLabel: 'Retour à l’accueil',
  search: {
    label: 'Rechercher',
    placeholder: 'Nom d’activité, chambre, vol, forfait…',
    catalogTitle: 'Catalogue',
    resultsTitle: 'Résultats',
    hint: 'Aucun produit disponible pour le moment.',
    browseLabel: 'Touchez un produit pour l’ajouter au panier.',
    resultsFor: (q: string) => `Résultats pour « ${q} »`,
    resultCount: (n: number) => (n === 1 ? '1 produit' : `${n} produits`),
    loadingLabel: 'Recherche…',
    emptyLabel: 'Aucun produit trouvé',
    emptyHint: 'Essayez un autre mot-clé ou changez le filtre.',
    clearSearchLabel: 'Effacer la recherche',
    errorLabel: 'Impossible de charger le catalogue',
    errorHint: 'Vérifiez votre connexion ou reconnectez-vous.',
  },
  filters: {
    all: 'Tous',
    activity: 'Activité',
    room: 'Chambre',
    flight_class: 'Vol',
    vehicle: 'Véhicule',
    cabin: 'Croisière',
    package: 'Forfait',
  },
  cart: {
    title: 'Panier',
    empty: 'Le panier est vide',
    emptyHint: 'Sélectionnez un produit dans le catalogue pour commencer.',
    itemCount: (n: number) => (n === 1 ? '1 article' : `${n} articles`),
    quantityLabel: (n: number) => (n === 1 ? 'Qté 1' : `Qté ${n}`),
    removeLabel: 'Retirer',
    clearLabel: 'Vider le panier',
    subtotalLabel: 'Sous-total',
    discountLabel: 'Remise',
    packageDiscountLabel: 'Remise forfait',
    totalLabel: 'Total',
    previewLoadingLabel: 'Calcul du total…',
    previewErrorLabel: 'Impossible de calculer le total',
    retryPreviewLabel: 'Réessayer le calcul',
    packageMixError:
      'Un forfait ne peut pas être combiné avec d’autres produits. Retirez le forfait ou videz le panier.',
  },
  customer: {
    sectionLabel: 'Client',
    walkInLabel: 'Client de passage',
    walkInHint: 'La vente sera enregistrée au nom de l’employé.',
    changeLabel: 'Changer',
    sheetTitle: 'Choisir un client',
    sheetSubtitle: 'Recherchez par e-mail ou nom, ou laissez un client de passage.',
    searchLabel: 'Rechercher',
    searchPlaceholder: 'E-mail ou nom du client…',
    searchHint: 'Saisissez au moins 2 caractères.',
    loadingLabel: 'Recherche…',
    emptyLabel: 'Aucun client trouvé',
    emptyHint: 'Vérifiez l’orthographe ou créez le compte côté admin.',
    errorLabel: 'Impossible de charger les clients',
    closeLabel: 'Fermer',
    selectWalkInLabel: 'Client de passage',
  },
  manifest: {
    sectionLabel: 'Manifeste voyageurs',
    subtitleEmpty: 'Aucun voyageur renseigné (optionnel)',
    subtitleCount: (n: number) =>
      n === 1 ? '1 voyageur renseigné' : `${n} voyageurs renseignés`,
    fillLabel: 'Renseigner',
    editLabel: 'Modifier',
    sheetTitle: 'Manifeste des voyageurs',
    sheetSubtitle: 'Renseignez l’identité des passagers et voyageurs.',
    travelerHeading: (n: number) => `Voyageur ${n}`,
    addTravelerLabel: 'Ajouter un voyageur',
    removeTravelerLabel: 'Supprimer',
    fillFromCustomerLabel: 'Utiliser le client sélectionné',
    fullNameLabel: 'Nom complet',
    fullNamePlaceholder: 'Ex. Jean Dupont',
    ageLabel: 'Âge',
    agePlaceholder: 'Ex. 32',
    sexLabel: 'Genre / Sexe',
    sexOptions: {
      empty: 'Non précisé',
      M: 'Homme (M)',
      F: 'Femme (F)',
      other: 'Autre',
    },
    nationalityLabel: 'Nationalité',
    nationalityPlaceholder: 'Ex. Congolaise, Française...',
    idNumberLabel: 'N° Passeport / Pièce d’identité',
    idNumberPlaceholder: 'Ex. AB123456',
    conditionsLabel: 'Conditions particulières / Santé',
    conditionsPlaceholder: 'Ex. Allergies, régime spécifique...',
    commentLabel: 'Remarques',
    commentPlaceholder: 'Notes...',
    saveLabel: 'Enregistrer le manifeste',
    closeLabel: 'Fermer',
  },
  promo: {
    sectionLabel: 'Code promo',
    placeholder: 'Saisir un code',
    applyLabel: 'Appliquer',
    removeLabel: 'Retirer',
    appliedHint: (code: string) => `Code appliqué : ${code}`,
  },
  config: {
    title: 'Configurer la ligne',
    closeLabel: 'Fermer',
    addLabel: 'Ajouter au panier',
    addRequestLabel: 'Demander cette réservation',
    assistedBadge: 'Sur demande',
    assistedHint:
      'Réservation sur demande : la date et les attributions seront configurées/confirmées par l’équipe après la demande.',
    directAvailabilityLabel: 'Disponibilités directes',
    requestedDateLabel: 'Date souhaitée',
    loadingLabel: 'Chargement…',
    quantityLabel: 'Quantité',
    startDateLabel: 'Arrivée',
    endDateLabel: 'Départ',
    dateLabel: 'Date',
    scheduleLabel: 'Créneau',
    slotLabel: 'Créneau disponible',
    sailingLabel: 'Départ croisière',
    seatsLabel: 'places',
    noSchedules: 'Aucun créneau disponible',
    noSlots: 'Aucun créneau disponible',
    noSailings: 'Aucune croisière disponible',
    selectSchedule: 'Choisissez un créneau',
    selectSlot: 'Choisissez un créneau',
    selectSailing: 'Choisissez une croisière',
    departureDateLabel: 'Date de départ',
    packageEndDateLabel: 'Date de fin',
    travelersLabel: 'Voyageurs',
    packageDurationHint: (days: number) =>
      days === 1 ? '1 jour' : `${days} jours`,
  },
  payment: {
    cashLabel: 'Espèces',
    cardLabel: 'Carte',
    cashProcessingLabel: 'Enregistrement…',
    cardProcessingLabel: 'Préparation du paiement…',
    cardPayLabel: 'Encaisser la carte',
    cardSheetTitle: 'Paiement par carte',
    cardSheetSubtitle: 'Saisissez ou présentez la carte du client.',
    closeCardLabel: 'Annuler',
    closeCardProcessingLabel: 'Annulation…',
    cardUnavailableLabel: 'Paiement carte indisponible (clé Stripe manquante)',
    checkoutErrorLabel: 'Impossible de finaliser la vente',
    cardErrorLabel: 'Le paiement carte a échoué',
    abandonStockReleasedHint: 'La réservation a été annulée et le stock libéré.',
    cancelAbandonErrorLabel: 'Impossible d’annuler la réservation en attente',
    previewRequiredHint: 'Attendez le calcul du total',
    dismissErrorLabel: 'Fermer',
  },
} as const;

export const posSaleSuccessPageConfig = {
  title: 'Vente enregistrée',
  subtitle: 'La réservation a été confirmée.',
  pendingSubtitle: 'Paiement reçu — confirmation en cours…',
  timeoutSubtitle:
    'La confirmation n’est pas encore arrivée. Le stock reste réservé tant que la réservation est en attente.',
  timeoutHint:
    'Si le client a déjà payé par carte, attendez ou actualisez. Sinon, annulez pour libérer le stock.',
  confirmingLabel: 'Confirmation de la réservation…',
  bookingLabel: 'N° réservation',
  paymentLabel: 'Mode de paiement',
  paymentCash: 'Espèces',
  paymentCard: 'Carte bancaire',
  newSaleLabel: 'Nouvelle vente',
  backToHomeLabel: 'Retour à l’accueil',
  refreshLabel: 'Actualiser',
  cancelPendingLabel: 'Annuler la réservation',
  cancelPendingProcessingLabel: 'Annulation…',
  cancelPendingErrorLabel: 'Impossible d’annuler la réservation',
  confirmedMeanwhileLabel: 'La réservation a été confirmée entre-temps.',
  receiptTitle: 'Reçu',
  printReceiptLabel: 'Imprimer le reçu',
  downloadPdfLabel: 'Télécharger PDF',
  downloadPdfHint: 'Le fichier PDF sera enregistré sur votre appareil.',
  downloadPdfProcessingLabel: 'Téléchargement…',
  downloadPdfErrorLabel: 'Impossible de télécharger le PDF.',
  emailFieldLabel: 'E-mail du destinataire',
  emailReceiptLabel: 'Envoyer le reçu par email',
  emailPlaceholder: 'client@exemple.com',
  emailInvalid: 'Saisissez une adresse e-mail valide.',
  emailSendingLabel: 'Envoi en cours…',
  emailSentHint: 'Le reçu a été envoyé par e-mail.',
  emailSendErrorLabel: 'Impossible d’envoyer le reçu par e-mail.',
} as const;
